### ISSUE TITLE
Execution failed for task ':react-native-google-analytics-bridge:processReleaseResources'.

### ISSUE THREAD

**Issue by edoko** [mcnamee/react-native-starter-app#100]
I have problem running app.

![image](https://user-images.githubusercontent.com/1365682/29028753-3bb6a17e-7bc0-11e7-8383-ecd5c11b4172.png)

I have Android sdk tools 23~25.

How should I fix it?

**Comment by guruganeshm-prft** [comment]
@edoko 
I ran into same issue, solution is to change your project folder name to minimal characters.
refer this thread https://github.com/mcnamee/react-native-starter-app/issues/64#issuecomment-289224815

**Comment by mcnamee** [comment]
@edoko Make sure you have exactly build tools `25.0.2` (from Android Studio > Tools > Android > SDK Manager > SDK Tools > Click show package details > then install the missing version/s)
