### ISSUE TITLE
Chrome Debugging doesn't load the app from launch screen

### ISSUE THREAD

**Issue by yasicmd** [mcnamee/react-native-starter-app#103]
When I turn on chrome debugging the app doesn't load from the launch screen It says a warning that given below

"Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. "

### Help us reproduce - tell us about your environment
I am running on a Linux system.
Debugging it with an Android device.

### Steps to reproduce
Turning on Chrome debugging

### Expected result
Shoud show the home screen
### Actual result

It shows a warning that 
"Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. "

**Comment by mcnamee** [comment]
Thanks @yasicmd - looks to be related to the Firebase library:

- https://github.com/firebase/firebase-js-sdk/issues/97

Will keep an eye on it

**Comment by mcnamee** [comment]
@yasicmd - it's a hack - but until Firebase resolve the issue, the following commit/lines prevent the annoying yellow popups:

https://github.com/mcnamee/react-native-starter-app/blob/40c964bc85896d384390eaea8b5d3b8581a7b00f/src/containers/Launch/LaunchView.js#L43-L46
