### ISSUE TITLE
How to hide navbar showing before auth screens?

### ISSUE THREAD

**Issue by dlucidone** [mcnamee/react-native-starter-app#105]
![screen shot 2017-09-16 at 10 01 09 pm](https://user-images.githubusercontent.com/9256365/30513975-9701d65a-9b2a-11e7-9745-ef568e9c338f.png)

**Comment by mcnamee** [comment]
@dlucidone your screenshot shows the iOS __Launch Screen__.

This is simply a jpg that's shown while the code is booting. You can replace this jpg in `/ios/StarterKit/Images.xcassets/Launch.imageset`. Or change it in XCode
