### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by Phil91** [mcnamee/react-native-starter-app#107]
### Help us reproduce - tell us about your environment

1. Mac
1. Latest version from Master

### Steps to reproduce

1. Clone git repository
1. Cd into repository
1. Run yarn install
1. Run yarn test

### Expected result

1. All tests should successfully pass

### Actual result

1. ![2017-09-18_08-33-22](https://user-images.githubusercontent.com/7672600/30531083-302ed3ec-9c4c-11e7-8726-73c2f1e0316e.png)

**Comment by mcnamee** [comment]
I'd love your help on it @Phil91 - PR?

**Comment by Phil91** [comment]
Sure happy to help
