### ISSUE TITLE
Where does the call goes while clicking on a tab item?

### ISSUE THREAD

**Issue by brainahdev** [mcnamee/react-native-starter-app#109]
Great StarterKit, I just looked the tab.js and i could not able to find the place where the event fires or called first when a tabitem is clicked. any idea?

**Comment by mcnamee** [comment]
Hi @brainahdev 
The tabs are setup and completely controlled by [React Native Router Flux](https://github.com/aksonov/react-native-router-flux). I'd suggest checking out the API docs over there - specifically tabs docs are [here](https://github.com/aksonov/react-native-router-flux/blob/v3/docs/API_CONFIGURATION.md#tabs).
