### ISSUE TITLE
Hide Navigation/Header Bar ?

### ISSUE THREAD

**Issue by EugeneLiang** [mcnamee/react-native-starter-app#11]
Hi there!

Great work on this starter app!

I was wondering if there's any way I can hide the navigation bar ?
For example, using this, when navigation to  the forms screen, is there a way to hide the `NavigationBar`  ?

Thanks!

**Comment by mcnamee** [comment]
Hi @EugeneLiang 
Sorry, not that I'm aware. Although you could ask the question over at the react-native-navbar page.

Thanks for the feedback!
