### ISSUE TITLE
Question: To access the state property must have the folder name in middle?

### ISSUE THREAD

**Issue by shic** [mcnamee/react-native-starter-app#115]
Question: Why in the state present the folder name ? i.e. when I read the sideMenu isOpen state, we should write: state.sideMenu.isOpen instead of state.isOpen.

In other projects that using redux I can read the state directly like state.isOpen.

The implementation in this project is good, but I am wonder what part of code add the folder name in the state?

Thanks!

![schermata 2017-10-10 alle 17 43 51](https://user-images.githubusercontent.com/4471626/31397740-1adfe51a-ade7-11e7-84d1-866f5c8a00ed.png)

**Comment by mcnamee** [comment]
Hi @shic 
The folders are purely for file organisation and don't affect the contents of redux at all.

You'll see in `/src/redux/index.js` that the code shows that when the reducers are combined, that `sideMenu` is included as an object (so `sideMenu` properties are underneath the `sideMenu` property of state).

I do that to somewhat namespace data. Eg. you could then have an `isOpen` property on both a `sideMenu` + `dropDown` + `ticket` component as an example.
