### ISSUE TITLE
No Licence

### ISSUE THREAD

**Issue by obromios** [mcnamee/react-native-starter-app#12]
In the description of this app, you call it a starter app and as boilerplate. Both these terms imply to me that you intend for people to freely use your software as a basis for their own apps. However, you have not included a licence agreement in your repository.  As github explains [here](https://help.github.com/articles/open-source-licensing/), if you do not choose a licence, then it considerably restricts what people can do with your code. If you really do intend for other people to freely use  your code I  have drafted an MIT licence below for you. I can also do a pull request to include this licence in your repository.

If you actually do not want people to use your code as a starter app, then I suggest that you include an appropriate explicit licence, as many people are not aware of the implications of a lack of licence in a github open source repository.

[licence.txt](https://github.com/mcnamee/react-native-starter-app/files/283158/licence.txt)

**Comment by mcnamee** [comment]
Done

**Comment by obromios** [comment]
👍
