### ISSUE TITLE
Dependency broken after 0.26

### ISSUE THREAD

**Issue by E-P1983** [mcnamee/react-native-starter-app#13]
Hi,

Right now, your dependency chain is broken. 

npm WARN react-native@0.26.2 requires a peer of react@15.0.2 but none was installed.

I have no idea why this is failing but it happens right after I cloned your updated project and ran npm install.

**Comment by mcnamee** [comment]
Thanks @E-P1983 - I've fixed by adding more specific versions of react/react-native.
Feel free to re-open if it's still not working for you.
