### ISSUE TITLE
SlideMenu: Slide to open bug

### ISSUE THREAD

**Issue by rafazundt** [mcnamee/react-native-starter-app#14]
If you use gesture to open the menu, clicks on menuItems renders the page with the menu still open.

**Comment by mcnamee** [comment]
Hi @rafazundt 
Sorry to hear.

Unfortunately I've tried cloning and running on 2 separate computers and can't replicate this. I have since just released v1 of this project, which includes Redux (and changes SideMenu to work with Redux), so I'd suggest giving it a try now.
