### ISSUE TITLE
React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Navigator`.

### ISSUE THREAD

**Issue by AppDev666** [mcnamee/react-native-starter-app#15]
React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Navigator`.
on both ios and android

**Comment by mcnamee** [comment]
Hi @AppDev666 
I've just freshly cloned the project and npm installed and can't see where/how you're getting that error. Can you please provide more information?

**Comment by AppDev666** [comment]
Hi @mcnamee,
I cloned yesterday and I am getting above error.When i click on "Signin/Sinup" button on first screen .
I am new to RN but some how I removed "comming soon" from first.load.js and set form.js.

BTW i see tab screen in screenshots but there is no tab in repo can you share.

**Comment by mcnamee** [comment]
Hi @AppDev666 
Ah ha - found it. Thanks for pointing it out. 

Thanks for also raising the screenshot inconsistency - I've fixed that, and also added the tabbar component I now use. The previous screenshot featured the RN iOS only tabbar, which I removed when migrating the project to support Android.

**Comment by AppDev666** [comment]
@mcnamee Thanks
