### ISSUE TITLE
Unhandled JS Exception: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `TabViewPage`.

### ISSUE THREAD

**Issue by AppDev666** [mcnamee/react-native-starter-app#16]
Unhandled JS Exception: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `TabViewPage`.

Hi @mcnamee I am getting similar error when i try to use tabs.js

**Comment by mcnamee** [comment]
Hi, Did you `npm update` after you recently pulled?
