### ISSUE TITLE
Suggestion: Scrollable tabs

### ISSUE THREAD

**Issue by npm-install** [mcnamee/react-native-starter-app#20]
Is there a easy way to achieve scrollable tabs? Currently it is trying to fit every tabs in same view.

I have a need to create something like below:

![MSN](https://lh5.ggpht.com/3SaVyBoPpQYO546oZ3zc3DH7omWw7fIo-nWkpQRLO5QKZ6k2PeGH6Bt7P4rqv1lcQwo=h900-rw)

**Comment by mcnamee** [comment]
Hi @npm-install - to make the top tabs horizontally scrollable - I'd suggest looking at wrapping them in a ScrollView.

Alternatively, head over to the _react-native-tab-view_ repo to ask the question:
https://github.com/react-native-community/react-native-tab-view
