### ISSUE TITLE
Upgrade to RN 0.32.0

### ISSUE THREAD

**Issue by navarroaxel** [mcnamee/react-native-starter-app#21]
Hi Matt, I'm new on react. Thanks for this project.

Can you update to the latest version of React-native and the other packages?

I have done this myself and it's working on Android, but I'm new here and I don't know what I need to check.

**Comment by mcnamee** [comment]
Hi @navarroaxel 
RN0.33 is due out in a few days (they have 2week release cycles). I'll aim to upgrade to that, on release. We've tried 0.32 on a project recently and had a few issues, so felt safer to go back to 0.31
