### ISSUE TITLE
Warning: Native component for "RCCToolBar" does not exist

### ISSUE THREAD

**Issue by LAMike310** [mcnamee/react-native-starter-app#23]
Hi I'm trying to run the example, after I ran npm install and opened the xcode project, I get an error when I start the simulator. After checking the console I found the error:

"ExceptionsManager.js:78 Warning: Native component for "RCCToolBar" does not exist

Is there something I missed when installing the module?

**Comment by mcnamee** [comment]
Hi @LAMike310 I've tried cloning and install freshly on 2 computers - one with Xcode 7 and another with Xcode 8, however they've both run successfully.

Perhaps try fresh again

**Comment by mahesh8488** [comment]
Did anyone get this working ?
