### ISSUE TITLE
Error on new install Application StarterKit has not been registered

### ISSUE THREAD

**Issue by tarkanlar** [mcnamee/react-native-starter-app#24]
Getting this error on brand new installation.

![image](https://cloud.githubusercontent.com/assets/213978/19411455/d4854da0-930a-11e6-9890-295e075a1e2e.png)

**Comment by mcnamee** [comment]
Hey @tarkanlar - I've just freshly cloned, installed and run and it's working for me (no error).

That error would usually appear if you've changed the name of the app without updating it's name/reference in `/index(.ios and .android).js` - i.e. you'd need to change `StarterKit` on line 14 to the name of the app:

```
AppRegistry.registerComponent('StarterKit', () => AppContainer)
```

Did you update anything after cloning?

I'd suggest trying again. If the issue still exists, please let me know:

- the platform you're testing on - Android or iOS?

**Comment by tarkanlar** [comment]
Oh sorry for late reply. I was my fault I guess, Solved the problem. Thanks a lot

**Comment by mcnamee** [comment]
No worries @tarkanlar - glad to hear you solved it!
Was the solution anything we can learn from?
