### ISSUE TITLE
Creating 2 or 3 column ListView

### ISSUE THREAD

**Issue by npm-install** [mcnamee/react-native-starter-app#26]
This really isn't an issue but the request. When it comes to CSS I am like:
![family-guy-window-blinds](https://cloud.githubusercontent.com/assets/8496184/19660429/95711a32-99e4-11e6-9aab-697604180950.gif)

Is there a quick way to convert the following listView to 2 or 3 column grid view?
![two](https://cloud.githubusercontent.com/assets/8496184/19660501/eecbb9fc-99e4-11e6-9f00-e91714151c08.png)

**Comment by mcnamee** [comment]
Hi @npm-install 
Yeah definitely possible. It's simply a case of:

- Styling each `_renderRow` element to be half or a third the width of the screen and
- Styling the ListView to 'float' rows next to each other - just by applying `flexDirection: 'row'` to the ListView `contentContainerStyle`

**Comment by npm-install** [comment]
Thanks for the pointers. Cheers!
