### ISSUE TITLE
'RCTRootView.h file not found after cloning project

### ISSUE THREAD

**Issue by robtg4** [mcnamee/react-native-starter-app#3]
This error comes up from your repo after cloning and following install instructions: 

![screen shot 2015-12-20 at 3 38 08 am](https://cloud.githubusercontent.com/assets/13613075/11917209/65901ba4-a6cb-11e5-8c97-fc6e63544e71.png)

**Comment by mcnamee** [comment]
Hi @robtg4 
I've just cloned, installed and run from scratch and didn't have any issues. I'm wondering if you've successfully run `sudo npm install` before running in Xcode? Is the local server running in terminal, accessible via localhost:8081?

If you have, have you altered anything outside of the instructions?
