### ISSUE TITLE
Menu items are not showing up

### ISSUE THREAD

**Issue by modev32** [mcnamee/react-native-starter-app#30]
menu can toggle in/out
but menu items are not showing up. only blank lines are showing.

although, i just run the app i didn't modify the content.

**Comment by mcnamee** [comment]
Sorry about that, give it a try now with the recent commits

**Comment by modev32** [comment]
do you mean branch v2 ?

**Comment by mcnamee** [comment]
Neither master or v2 branches don't contain the issue, however I was referring specifically the master branch - [this commit](https://github.com/mcnamee/react-native-starter-app/commit/6154cbbf86785f5610d41166badee7317b3942ef) fixed your issue.
