### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by RodrigoRMG** [mcnamee/react-native-starter-app#32]
I can´t run in adroid:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-google-analytics-bridge:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Android\android-sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Some help? :(

**Comment by mcnamee** [comment]
Hi @RodrigoRMG  
I've just git cloned a fresh install and built and it's worked as expected.

It could be a couple of things, both related to your Android environment:

## 1. Google Play Services
Do you have Google Play Services installed? I have a [tutorial here](https://medium.com/pvtl/react-native-android-development-on-mac-ef7481f65e47#.wpc99qyhz) which explains in step 4.

## 2. Outdated Environment
I'm wondering if it's related to an outdated Java SDK or Android Virtual Device (in my experience, React Native tends to prefer bleeding edge).

I've included a screenshot of my AVD settings, for you to compare.

<img width="549" alt="screen shot 2016-12-02 at 6 55 05 am" src="https://cloud.githubusercontent.com/assets/1809236/20812220/7fe50390-b85c-11e6-82e5-9cccd2ecc069.png">

Love to hear how you get on
