### ISSUE TITLE
Could not compile build file: unable to resolve class com.android.build.OutputFile

### ISSUE THREAD

**Issue by shaweiguo** [mcnamee/react-native-starter-app#33]
Here's what I'm seeing after run react-native run-android:
build file 'D:\react-native-starter-app\android\app\build.gradle': 3: unable to resolve class com.android.build.OutputFile
 @ line 3, column 1.
     import com.android.build.OutputFile
     ^

  1 error

**Comment by mcnamee** [comment]
Hi @shaweiguo 
I've just git cloned a fresh install and built and it's worked as expected.
I'm wondering if it's related to an outdated Java SDK or Android Virtual Device (in my experience, React Native tends to prefer bleeding edge).

I've included a screenshot of my AVD settings, for you to compare.

<img width="549" alt="screen shot 2016-12-02 at 6 55 05 am" src="https://cloud.githubusercontent.com/assets/1809236/20812220/7fe50390-b85c-11e6-82e5-9cccd2ecc069.png">

Love to hear how you get on
