### ISSUE TITLE
Javascript alert not working in webview in android

### ISSUE THREAD

**Issue by obromios** [mcnamee/react-native-starter-app#34]
I have an app based on your react-native-starter-app. It has a JavaScript alert in one of the webviews. It works in IOS but not android. I have changed the ```proguard-rule.pro``` file as follows

class:
-keepclassmembers class fqcn.of.javascript.interface.for.webview {
   public android.webkit.WebView, startActivity, android.webkit.WebChromeClient, android.webkit.JsResult;
}
and done a ```react-native run-android``` but the alert is still not working in the android app.  How do I do this, and what are the fully qualified class name to the JavaScript Interface. I am pretty sure I have not modified the Javascript interface in my version of the app.

**Comment by mcnamee** [comment]
Hi @obromios 
Sorry, I'm not sure where the issue is arriving with this one. I would suggest using the [React Native Alert](https://facebook.github.io/react-native/docs/alert.html) instead of the standard JS Alert.

Syntax is basically the same - instead of `alert('La di dah')` it's just `Alert.alert('Title', 'Description')`.

**Comment by obromios** [comment]
I am not sure this would help. The problem occurs in a WebView that that loads an html page from the server. The html page has a combination of html and javascript.  Simple pages use javascript alerts, but other have much more complex javascript, so I need javascript to work from within the WebView. It does for IOS.

**Comment by mcnamee** [comment]
Ah ok, I'd suggest this would be an issue with either your environment OR the React Native webview component - not the custom components used in this repo.

However to isolate the issue - I suggest creating a fresh React Native project and opening the same webview from that project - does the issue still exist?

**Comment by obromios** [comment]
I will try a fresh project and see what happens.
