### ISSUE TITLE
Adding an example that involves back button

### ISSUE THREAD

**Issue by sgaurav** [mcnamee/react-native-starter-app#4]
Can you please push an extra module that involves using back button. If no, can you help me understand how it is to be done. I will try and when working fine will send a PR.

**Comment by mcnamee** [comment]
Hi
By default when you first run the app, you can tap on the text that says "This will replace the screen to test the back button". This will push the screen, showing the back button on the new screen.

**Comment by sgaurav** [comment]
Extremely sorry, failed to recognise that text is clickable. Thanks for prompt help.
