### ISSUE TITLE
Why is app so slow?

### ISSUE THREAD

**Issue by jsam** [mcnamee/react-native-starter-app#44]
I just tried newest release of the project and both in ios simulator and on android device demo app is really slow.

Slow loading, rendering of images and transitions are laggy.

Any suggestions on how to make it faster?

**Comment by Jean-PierreGassin** [comment]
Hey @jsam,

Could you check if you have slow transitions enabled? (CMD + T)

Are you keeping the debugger console focused in the background? Having it as an un-focused tab will cause the simulator to load slowly.

**Comment by mcnamee** [comment]
Hi @jsam 
I think I may know what you're referring to. When you're in Debug mode, you need to have the Debugger (Chrome Dev Tools) open. Plus as @Jean-PierreGassin said, the debugger should be in a focused tab.

Unfortunately it's a React Native thing we're living with at the moment.

**Comment by LancCJ** [comment]
打开调试模式  you need to have the Debugger (Chrome Dev Tools) open 像这个作者说的那样
