### ISSUE TITLE
App renaming

### ISSUE THREAD

**Issue by StefanWallin** [mcnamee/react-native-starter-app#45]
It would be handy to document or automate the renaming of the starterkit, we wouldn't want multiple versions of "Starter-Kit" ending up on the app Stores" ;)

I'm trying to get where the name makes sense so I can write a script that automates it, this is how far I've come:

1. Rename the value of the name property in `./Package.json`.
1. Run `react-native upgrade`.
1. Run `react-native link`.
1. Remove Starter-kit source files:
    1. The iOS project files: `rm -rf ios/StarterKit*`
    1. The Android project source files: `rm -rf android/app/src/main/java/com/starterkit/`
1. Change name of component in the `AppRegistry.registerComponent`-call for iOS.

But fonts don't work and stuff breaks left and right.

I've also tried following this answer without success: http://stackoverflow.com/questions/33370175/how-do-i-completely-rename-an-xcode-project-i-e-inclusive-of-folders

Do you know what's needed to rename the app completely?

**Comment by mcnamee** [comment]
Hi! It's funny you ask that, I just added that doc last week. Jump into the develop branch and there should be a link in the readme to renaming the app.

I haven't merged to master yet as I was waiting on my PR from the Google Analytics Npm module to be accepted. Should be releasing to master soon.

**Comment by StefanWallin** [comment]
Great stuff! Thanks. Too bad I did not find that tool in my googling.
