### ISSUE TITLE
Unable to launch iOS app with latest code from repo

### ISSUE THREAD

**Issue by dhammikab** [mcnamee/react-native-starter-app#49]
i cloned the repo, ran npm install in the folder consenting the source, launched Xcode and tried to launch the app. I received the following error: [Screen shot of the emulator has been attached.
![simulator screen shot jan 20 2017 9 19 29 pm](https://cloud.githubusercontent.com/assets/1028364/22171181/7f667860-df56-11e6-9160-6bac2832b3de.png)

2017-01-20 21:10:44.060 [info][tid:main][RCTBatchedBridge.m:72] Initializing <RCTBatchedBridge: 0x608000196240> (parent: <RCTBridge: 0x6080000b95c0>, executor: RCTJSCExecutor)
objc[47790]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x123b69998) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x12398b880). One of the two will be used. Which one is undefined.
2017-01-20 21:10:44.999 [error][tid:com.facebook.react.JavaScript] `View` has no propType for native prop `RCTView.aspectRatio` of native type `float`
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.
2017-01-20 21:10:45.005 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: `View` has no propType for native prop `RCTView.aspectRatio` of native type `float`
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.
2017-01-20 21:10:45.494 [info][tid:main][RCTRootView.m:249] Running application StarterKit ({
    initialProps =     {
    };
    rootTag = 1;
})

**Comment by dhammikab** [comment]
this was an issue due to another version of react packager was running.
Following the instructions onhttp://stackoverflow.com/questions/38520003/react-native-no-proptype-for-native-prop-rctview-maxheight

resolved my issue.

**Comment by mcnamee** [comment]
No worries. I've experienced the same thing myself, many times.

Glad to hear you got it sorted!
