### ISSUE TITLE
Upgrade to react native 0.20?

### ISSUE THREAD

**Issue by insaneinc01** [mcnamee/react-native-starter-app#5]
Hello, thanks for putting this together. Its a great learning resource for someone starting out with react native and wanting to build a full fledged app. 

I tried upgrading to 0.20 and got into a few issues. Mainly this one:
`babelHelpers.objectDestructuringEmpty is not a function`

Any tips on whats the best way to upgrade to the latest react-native version?

**Comment by mcnamee** [comment]
Hi!

Thanks for giving me the push to upgrade. I've been meaning to update dependencies for a whilst, but didn't know if anyone actually used the project, to make it a priority.

I'll update in the coming few days and comment back when done. I've updated RN in a few of my projects recently and know it's never pain free.

Matt

**Comment by insaneinc01** [comment]
Oh wow, that would be awesome!
I found your project when I was almost about to give up on react-native. This is great. Thanks!

**Comment by mcnamee** [comment]
Hi @insaneinc01 
I've just pushed the update where I've updated all dependencies.
Please let me know if you notice any issues.

Matt
