### ISSUE TITLE
Issues with react-native run-android

### ISSUE THREAD

**Issue by TheRealJAG** [mcnamee/react-native-starter-app#50]
Getting the following errors

C:\Users\Personal\Documents\Projects\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_icon_dark.xml:5:27-80 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_disabled').
C:\Users\Personal\Documents\Projects\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_icon_light.xml:5:27-81 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_disabled').
C:\Users\Personal\Documents\Projects\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_icon_light.xml:8:27-80 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_pressed').
C:\Users\Personal\Documents\Projects\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_text_dark.xml:7:27-80 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_disabled').
C:\Users\Personal\Documents\Projects\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_text_light.xml:5:27-81 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_disabled').
C:\Users\Personal\Documents\Projects\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_text_light.xml:8:27-80 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_pressed').

**Comment by TheRealJAG** [comment]
More

* What went wrong:
Execution failed for task ':react-native-device-info:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Personal\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1

**Comment by mcnamee** [comment]
Hey @TheRealJAG 
Looks like a strange one. I've cloned fresh and been able to run successfully in Android.

From a quick Google, the errors line up with others who indicate it's an emulator issue. Have you got Google Play Services installed (it's required for various packages like Google Analytics)?

I've written a post [over here](https://medium.com/pvtl/react-native-android-development-on-mac-ef7481f65e47#.e27xbfz66) which may help to debug if you've got your Android environment ready to go.

**Comment by neosekar** [comment]
Hey @TheRealJAG,
  Have a look at this https://github.com/mcnamee/react-native-starter-app/issues/52#issuecomment-275842893. It may solve your issue
