### ISSUE TITLE
Favourites without login

### ISSUE THREAD

**Issue by botsbuzz** [mcnamee/react-native-starter-app#51]
I turned off JWT Auth in /lib/api.js.
How to use the favourites feature?

**Comment by mcnamee** [comment]
Hi there @botsbuzz 
Favourites are saved to the API, against a member's account. You're therefore required to authenticate with the API (via JWT) to use the favourites feature.

If required, for the app you're writing, you could re-write the favourites feature to persist to Redux, and remove the post to the API stuff.

**Comment by botsbuzz** [comment]
Thank you so much @mcnamee !
I have to re-write favourites feature to persist to Redux.

Great starter kit!
