### ISSUE TITLE
error when react-native run-android

### ISSUE THREAD

**Issue by luisfarfan** [mcnamee/react-native-starter-app#52]
:react-native-device-info:processReleaseResourcesC:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_icon_dark.xml:5:27-80 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_disabled').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_icon_dark.xml:8:27-79 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_pressed').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_icon_dark.xml:13:27-78 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_normal').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_icon_dark_focused.xml:14:29-80 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_normal').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_icon_light.xml:5:27-81 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_disabled').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_icon_light.xml:8:27-80 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_pressed').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_icon_light.xml:13:27-79 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_normal').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_icon_light_focused.xml:14:29-81 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_normal').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_text_dark.xml:7:27-80 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_disabled').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_text_dark.xml:10:27-79 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_pressed').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_text_dark.xml:15:27-78 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_normal').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_text_dark_focused.xml:14:29-80 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_normal').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_text_light.xml:5:27-81 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_disabled').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_text_light.xml:8:27-80 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_pressed').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_text_light.xml:13:27-79 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_normal').
C:\Users\lfarfan\Desktop\projects\ReactNative\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.0.1\res\drawable\common_google_signin_btn_text_light_focused.xml:14:29-81 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_normal').

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-device-info:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\lfarfan\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 54.606 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:11424) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined
(node:11424) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by neosekar** [comment]
Hi luisfarfan,
   I already same kind of issue when run-android. In my case i fixed by changing directory of source like I initially got the build issue in **C drive** desktop folder, then i changed into **D drive** it works without any issue.
Sorry for bad english. Hope this helps to you.

**Comment by RoryShively** [comment]
This helped me out if you dont have Build Tools 23.0.1 installed http://stackoverflow.com/questions/36683726/failed-to-find-build-tools-revision-23-0-1/39828902
