### ISSUE TITLE
Needed firebase integration

### ISSUE THREAD

**Issue by neosekar** [mcnamee/react-native-starter-app#53]
Hi,
  I checked this starter app is really cool and i am new to react native. In this app really helpful for me to learn react native. I already worked on ionic framework in **firebase** integration is really simple but in react native redux strcture i can't figure out firebase integration. If you integrate firebase, then it would be really helpful for me. I can sure about that lot of them looking best way of integrating firebase into react native because out there to find a way to efficient integration of firebase in react native redux is not a simple task.
 I am really looking for you guys. Thanks for the app.

**Comment by mcnamee** [comment]
Thanks @neosekar 
I don't have any plans on switching this boilerplate to Firebase. In saying that, it still provides all the tools necessary to do a fairly simple switch to Firebase (or any other API for that matter).

From a quick Google, I found [this article](https://firebase.googleblog.com/2016/01/the-beginners-guide-to-react-native-and_84.html) which will help to get you going.
