### ISSUE TITLE
Hide tabBar

### ISSUE THREAD

**Issue by moisesnandres** [mcnamee/react-native-starter-app#54]
Maybe it is dumb question but how can I hide the navbar ? I try to remove it but that gives me an error.

**Comment by mcnamee** [comment]
Hi @moisesnandres 
Depends if you're referring to the navbar or tabbar?

Either way, both are controlled by [react-native-router-flux](https://github.com/aksonov/react-native-router-flux) and available for modification in the `/src/navigation` directory.

- The tabs are created by wrapping `<Scene />`'s in a scene with a `tabs` prop
- You can hide a navbar by adding  a `hideNavbar` prop to any scene

**Comment by moisesnandres** [comment]
The tabbar but I found a solution, setting its height to 0 in src/theme/sizes.js
Because when I remove the scene in tabs.js that gives me an error with children[0].
Thanks for answering!

**Comment by caciobanita** [comment]
Heloo,
How to render only the SideMenu, i don't need the tabBar?
