### ISSUE TITLE
Why is it so slow?

### ISSUE THREAD

**Issue by collinglass** [mcnamee/react-native-starter-app#55]
I loaded it on my iOS simulator and it takes multiple seconds to switch screens?

**Comment by mcnamee** [comment]
Please see issue #44

**Comment by markmssd** [comment]
Having the same problem... deployed it to my iPhone 7 Plus and it's also slow. Any suggestions?

**Comment by markmssd** [comment]
Tried with ```react-native run-ios --configuration Release``` and it's solves it for me!

**Comment by mcnamee** [comment]
Thanks @markmssd 
Just repeating the notes from issue #44 and summarising:

When you're in __Debug mode__, you need to have the Debugger (Chrome Dev Tools) open as it logs info to the console (the debugger should be in a focused tab).

When you're wanting to __Release__/test on an actual device, you need to switch to React Native's Release configuration by either:

- In Xcode - set the Build Configuration (CMD+SHIFT+,) to release
- As @markmssd suggested - add the `--configuration Release` flag to your `react-native` command
