### ISSUE TITLE
@Containers Issue

### ISSUE THREAD

**Issue by abdelwehed** [mcnamee/react-native-starter-app#56]
Hello @mcnamee,

First i want to thank you for this great starter app. I had implement everything correctly and i was able to run and modify many things, then i added a new container inside containers folder like so:
 --containers
    --abscence
       --AbscenceContainer.js
       --Container1View.js
Here when calling this.props.user i got undefined and i didn't get it why. Here are the attached files i added.
-------------------AbscenceContainer.js----------------------------
`/**
 * Launch Screen Container
 *
 * React Native Starter App
 * https://github.com/mcnamee/react-native-starter-app
 */
import { connect } from 'react-redux';

// Actions
import * as RecipeActions from '@redux/recipes/actions';
import * as UserActions from '@redux/user/actions';

// The component we're mapping to
import AbscenceRender from './AbscenceView';

// What data from the store shall we send to the component?
const mapStateToProps = state => ({
  user: state.user,
});

// Any actions to map to the component?
const mapDispatchToProps = {
  absence: RecipeActions.getAbscencesAll,
};

export default connect(mapStateToProps, mapDispatchToProps)(AbscenceRender);`

---------------------AbscenceView.js----------------------------

`/**
 * Launch Screen
 *  - Shows a nice loading screen whilst:
 *  - Checking if user is logged in, and redirects from there
 *
 * React Native Starter App
 * https://github.com/mcnamee/react-native-starter-app
 */
import React, { Component, PropTypes } from 'react';
import {
  View,
  ListView,
  Image,
  StatusBar,
  StyleSheet,
  ActivityIndicator,
} from 'react-native';
import { Actions } from 'react-native-router-flux';
import AppAPI from '@lib/api';
// Consts and Libs
import { AppStyles, AppSizes } from '@theme/';

/* Styles ==================================================================== */
const styles = StyleSheet.create({
  launchImage: {
    width: AppSizes.screen.width,
    height: AppSizes.screen.height,
  },
});

/* Component ==================================================================== */
class AbscenceView extends Component {
  static componentName = 'AbscenceView';

  static propTypes = {
    getAbscencesAll: PropTypes.func.isRequired,
  }

    constructor(props) {
    super(props);

    this.state = {
      loading: true,
      visitedRoutes: [],
      isRefreshing: true,
      dataSource: new ListView.DataSource({
        rowHasChanged: (row1, row2) => row1 !== row2,
      })
    };
  }

  componentDidMount = () => {
     _**console.log('user token '+this.props.user.token);**_//this is where i get the error
    // Show status bar on app launch
  //  StatusBar.setHidden(false, true);

    // Try to authenticate based on existing token
    /*this.props.login()
      // Logged in, show index screen
      .then(() => Actions.app({ type: 'reset' }))
      // Not Logged in, show Login screen
      .catch(() => Actions.authenticate({ type: 'reset' }));
      params,body
  }*/
}
  render(){

    return (<View style={[AppStyles.container]}>

        <ActivityIndicator
          animating
          size={'large'}
          color={'#C1C5C8'}
        />

    </View>
  )
  };
}

/* Export Component ==================================================================== */
export default AbscenceView;
`

Thank ou in advance

**Comment by mcnamee** [comment]
Hi,
It looks as though you're using the launch screen. The launch screen is the first screen to load, when no data exists in redux. The first thing this component does, is to try and login to the API, if successful - it puts user into redux, if not, user will remain undefined.

Check your Chrome debug console, to see if user actually exists.
