### ISSUE TITLE
Device orientation locked?

### ISSUE THREAD

**Issue by yazonnile** [mcnamee/react-native-starter-app#6]
Sorry, maybe for a dummy question.
How to unlock orientation change? Im trying it on XCode emulator - and it's not changing (default Awesome project does).

Thx anyway! Great starter!

**Comment by mcnamee** [comment]
Hi,
Not a stupid question! This editable in Xcode, on the project overview screen (where you set things like the project name, launch screen etc.). There's checkboxes where you can select which the orientation the app is allowed in.

**Comment by yazonnile** [comment]
Yes. Thx

**Comment by mcnamee** [comment]
Hi @yazonnile 
Just letting you know that I just pushed an update which fixed the device orientation issue. I realise once you unlocked it, it may have looked a little funny on rotation - this is now resolved
