### ISSUE TITLE
Renaming app fails

### ISSUE THREAD

**Issue by GlenHughes** [mcnamee/react-native-starter-app#62]
Hi,

Thanks for developing this starter app, it's really helpful!

I'm trying to rename the app and I keep getting the following error:

`react-native-rename MyAppName
The app_name value in ./android/app/src/main/res/values/strings.xml must be the same with ./ios/AppFolderName before renaming the app.
ex. ./ios/CoolApp  --->  <string name="app_name">CoolApp</string>
and try running the command again with you new app name.
ex. react-native-rename "Awesome App"
If your're using Windows OS, please run this command using Git Bash or Cygwin or other equivalent that runs Linux commands.
`

Any help would be greatly appreciated.

**Comment by wzuo** [comment]
I've experienced same issue while cancelling renaming shortly after executing this command and relaunching it again. Which OS do you use?

**Comment by GlenHughes** [comment]
Windows 10

**Comment by wzuo** [comment]
this may be the issue. did you try to clone repo and run this command on pristine repository? it works for me on Linux

**Comment by GlenHughes** [comment]
I can try again with a fresh clone to check. I will let you know what happens

**Comment by GlenHughes** [comment]
Hey, thanks for you help on this. I've completed a fresh clone and it worked first time. I must of changed something that's affecting it. It maybe worth adding to: https://github.com/mcnamee/react-native-starter-app/blob/master/docs/renaming.md that you should make sure it's a clean install.
