### ISSUE TITLE
\Android\sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by BrianJVarley** [mcnamee/react-native-starter-app#64]
Hi @mcnamee, Running the react-native-starter-app it fails in my environment with the error:
```
:react-native-device-info:processReleaseResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-device-info:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Brian\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
```

Is there a way to get a more detailed stack trace using the `react-native run-android` command? At the moment this error doesn't give enough detail as to what's up. 

Thanks

**Comment by Jean-PierreGassin** [comment]
Hey @BrianJVarley,

Have you tried running with the --stacktrace option in your gradle build parameters? Perhaps that will give you/us a better idea of what's going on here.

If that doesn't work you can try building the device-info package separately or re-link it to the project; let me know how you go.

**Comment by BrianJVarley** [comment]
@Jean-PierreGassin That's what I'm not quite sure of. How do I add the ` --stacktrace ` option to gradle. In the `build.gradle` file somewhere? Or another file?

**Comment by mcnamee** [comment]
Hi @BrianJVarley 
Thanks for sharing your `--info`. I believe the issue relates specifically to `react-native-device-info` and may be resolved by upgrading your Android environment.

I'm running the latest Android SDK and Android Build Tools, and it all looks to be running well.

The following screenshots show my current Android SDK + Emulator settings (where this project runs without errors).

![sdk](https://cloud.githubusercontent.com/assets/1809236/24088543/5f2fa7e8-0d77-11e7-97e5-d94b89c254d3.png)

![emulator](https://cloud.githubusercontent.com/assets/1809236/24088537/50db7a6e-0d77-11e7-9596-f6da20c67e53.png)

**Comment by vvasiloud** [comment]
I encountered the same problem in a real device. If you managed to fix this problem let us know.

**Comment by Rizwanilahi** [comment]
Solved: Thanks @vvasiloud

**Comment by Syldel** [comment]
Thank you. On Windows, some file path are too long. Move the project to the root solve the problem. :-)

**Comment by GastonEDiaz** [comment]
@vvasiloud 
How would that be? 
What folder would I have to move it to? Thanks

**Comment by vvasiloud** [comment]
@GastonEDiaz Move it to root (C://) for example and see if it works

**Comment by RajaSaravanan** [comment]
Putting the app to the root folder example C:\\ solved the issue. Windows is always developer unfriendly. :-(
