### ISSUE TITLE
something about import xxx from ‘@xxx’

### ISSUE THREAD

**Issue by rccoder** [mcnamee/react-native-starter-app#66]
Hi，I found you use `import xxx from '@xxx'` in the code

such as:

https://github.com/mcnamee/react-native-starter-app/blob/master/src/index.js#L22

Then, I found in the redux folder，you write package.json with:

```
{
    "name": "@redux"
}
```

So，I just test it in my work. Happily, It is Ok in React Native Works

But in other work just like react，It is not ok and will show the log:

`Moudle not found : '@xxx'`

So, I want to know why can use this method in RN works? and How to use it right in another works like React

**Comment by mcnamee** [comment]
Hi @rccoder - I believe this is specific to React Native.

I'll keep this open for a bit, in case anyone else has information on adding similar support to a web project, before closing.

**Comment by wkw** [comment]
I was curious and poked around a bit in RN's issues. I suspect you're right that it's RN specific.
Maybe hint here: https://github.com/facebook/react-native/issues/8623

I would like to know more about it. Also curious how @rccoder learned about it.

**Comment by rccoder** [comment]
@wkw  could use webpack alias to hack it

**Comment by rccoder** [comment]
https://blog.callstack.io/a-cure-for-relative-requires-in-react-native-2b263cecf0f6
