### ISSUE TITLE
Adding conditional right nav buttons?

### ISSUE THREAD

**Issue by tharrington** [mcnamee/react-native-starter-app#7]
If I am make a standard master-detail application with multiple sets of master-detail records. How can I conditionally add a right-nav button with a "+" to load a detail view to create a new record?

**Comment by tharrington** [comment]
I ended up adding it in the index.ios.js file, but the image is margined off the screen. It's about 20 pixels too far right. Any idea what would cause this?

**Comment by mcnamee** [comment]
Hi,
Awesome, I'd probably do it the same way. 

RE: styling, you should be able to simply create a new style for this new button. You're possibly using the same styles from the left button, which has the left margin.

**Comment by tharrington** [comment]
you are right... thank you!
