### ISSUE TITLE
Undefined is not an object (evaluating 'state.recipe.meals')

### ISSUE THREAD

**Issue by caciobanita** [mcnamee/react-native-starter-app#73]
Hello, i try to use your boilerplate, but i get this Undefined is not an object (evaluating 'state.recipe.meals') in BrowserContainer.js 
// What data from the store shall we send to the component?
const mapStateToProps = state => ({
  meals: state.recipe.meals,
});

**Comment by mcnamee** [comment]
Hi @caciobanita 
Sorry I can't replicate this. I've just:

- Cloned from master
- `npm install`
- `react-native run-ios`

and I can't find the error

**Comment by caciobanita** [comment]
Tanks for replay. Can you explain 
const mapStateToProps = state => ({
meals: state.recipe.meals,
});
What each one refers to, in special meals: state.recipe.meals.
maybe can debug it.

**Comment by mcnamee** [comment]
Hi @caciobanita 
That's Redux - it's passing the contents of meals (from the Redux store) into the container.

[Here's the link](https://github.com/reactjs/react-redux) to Redux if you want to learn more.
