### ISSUE TITLE
How to implement side menu?

### ISSUE THREAD

**Issue by caciobanita** [mcnamee/react-native-starter-app#74]
How to change the TabBar from Recipes  in SideMenu scenes?
Any guidance?

**Comment by mcnamee** [comment]
Sure @caciobanita 

Take a look the respective package - [React Native Router Flux](https://github.com/aksonov/react-native-router-flux). Here's a  link to where you'll find their docs on the TabBar: 

https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md
