### ISSUE TITLE
Wordpress API customization unclear

### ISSUE THREAD

**Issue by RickBross** [mcnamee/react-native-starter-app#77]
Where does the 'recipe_meal' key come from on the response?

I started my own Wordpress and got the JSON and JWT plugins working... but now I am just pointing to `/wp-json/wp/v2/posts` so it doesn't know what `recipe_meal` is... is it added by us in redux or does it come from the API?

Also, how do you create the recipes endpoints? I need to create custom endpoints aswell.

my posts:
<img width="284" alt="screen shot 2017-05-25 at 4 54 44 pm" src="https://cloud.githubusercontent.com/assets/4257160/26470223/e69e725a-416a-11e7-8f6d-6c72eece609d.png">

your "recipes":
<img width="497" alt="screen shot 2017-05-25 at 4 54 39 pm" src="https://cloud.githubusercontent.com/assets/4257160/26470222/e69966f2-416a-11e7-89de-d5cba9bc8aab.png">

**Comment by mcnamee** [comment]
Hey @RickBross 
In Wordpress, I created a Post Type called `Recipes`, with the taxonomy of `Meals`. It's fairly straight-forward to create and add post types to the Rest API using [Custom Post Type UI](https://en-au.wordpress.org/plugins/custom-post-type-ui/). I also used Advanced Custom Fields to add the additional fields like `ingredients` and `method`.

The data you're referring to came down from the API, and then added to redux in the respective Action/Reducer.

Hope that helps
