### ISSUE TITLE
User login to http://wp-api.mcnam.ee

### ISSUE THREAD

**Issue by guizmo** [mcnamee/react-native-starter-app#79]
Hi there

I created an account on your API to test the user login part.
But i get an error message when trying to login : "Response returned is not valid JSON"
Could you tell me what i am doing wrong please ?
![screen shot 2017-06-03 at 19 13 19](https://cloud.githubusercontent.com/assets/699063/26751960/db70e64c-4890-11e7-9466-24495766eea8.png)

**Comment by mcnamee** [comment]
Hi
I noticed a similar thing last week. The Wordpress API is currently broken due to a Wordpress update :(

I tried to resolve, but couldn't get the WP plugins working. I'm hoping another WP/plugin update will fix, otherwise I'll need to look for another API example to showcase how to use with the StarterKit.

**Comment by guizmo** [comment]
How okay. thanks for the quick reply.

**Comment by mcnamee** [comment]
Hi @guizmo 
I've re-written the networking/data example in the app, to show off [Firebase](https://firebase.google.com/). You should be able to clone from master, and follow the instructions from the updated Readme.

**Comment by guizmo** [comment]
Thanks Matt !

**Comment by guizmo** [comment]
Ok i'm going to ask you one last question...
Have you tried cloning master and starting from scratch ?

I get an error and it is the same on other boilerplates like https://github.com/bosung90/react-native-router-flux-example

![screen shot 2017-06-12 at 18 28 11](https://user-images.githubusercontent.com/699063/27025339-de3cae76-4fa5-11e7-84df-bddcf8429cd1.png)

**Comment by openqubit** [comment]
@guizmo Must you login to the a wordpress app?. If you are just using a php backend or node js one, i can share on how its done.

**Comment by guizmo** [comment]
no this error is on first launch... Matt's latest update removed the (worpress) api to use Firebase

**Comment by openqubit** [comment]
Oh ok. Haven't had a chance to look at that.

**Comment by mcnamee** [comment]
@guizmo - I've tried fresh on a different computer and have reproduced.
Downgrading/upgrading some of the dependencies helped for me (I've just pushed the working version to Master).

I also noted that React has deprecated PropTypes - so you'll see some other updates in there for that warning.

**Comment by guizmo** [comment]
Man you're DA BOMB... Yes i have noticed the PropTypes warning on other
projects
