### ISSUE TITLE
Login Page Before Sidemenu

### ISSUE THREAD

**Issue by tharrington** [mcnamee/react-native-starter-app#8]
Add support for a login/signup page that does not have the sidemenu / navbar. Conditional check before proceeding to navbar/sidemenu.

I'm new to react and react native, this is a great starter. Thanks!

**Comment by tharrington** [comment]
have any thoughts on the solution to this?

**Comment by mcnamee** [comment]
Hi!
For different apps, I've done this a couple of different ways. 

One that 'required' login to proceed - simply does a check on app startup (or on mount of the index file) to see if the user is logged in, if not, in the render method, it changes the output with a login screen. The login screen is the window height and width with a background colour, to essentially mask the nav bar (and therefore prevent the user from doing anything else.

In another app which only suggests login for certain features: in my API class, when the API responds with an unauthorized return (i.e. The user has asked to do something, but not logged in) - I push the navigator to a login screen (I also changed the transition to a floatfrombottom transition).

That's all to say that it does support what you're requesting :)

Hope that helps

**Comment by philohelp** [comment]
Leaving default user/pass in the fields so that user only has to press the login button (or choose to logout or log a different user) would be my favorite solution.

**Comment by mcnamee** [comment]
Hi @philohelp 
Yes, you could definitely do that by saving the login credentials to AsyncStorage, in a similar way to the forms.ios.js file. Then whenever the login screen is brought up, simply pull in the credentials from AsyncStorage.

**Comment by mcnamee** [comment]
Hi @tharrington and @philohelp 
Just an FYI to let you know that I've pushed an updated which shows a splash screen on first load, which hides the navbar. It mightn't be the solution for you, however it's the login/signup splash screen that I often use.

**Comment by tharrington** [comment]
Thanks, I tried pulling and seeing the updates... but there is an error when I launched. It might not be related to the work you've put in:

> 
> `TabBarItemIOS` has no propType for native prop `RCTTabBarItem.renderAsOriginal` of native type `BOOL`
> If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.
>
