### ISSUE TITLE
Two buttons sharing a row 

### ISSUE THREAD

**Issue by openqubit** [mcnamee/react-native-starter-app#81]
I have two buttons that look like this

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/OBdzj.png

This is the code 

    render = () => (
        <Image
          source={require('../../images/login.jpg')}
          style={[AppStyles.containerCentered, AppStyles.container, styles.background]}
        >
          <Image
            source={require('../../images/logo.png')}
            style={[styles.logo]}
          />
          <Spacer size={200} />
          <View style={[AppStyles.row, AppStyles.paddingHorizontal]}>
            <View style={[AppStyles.flex1]}>
              <Button
                title={'Login'}
                icon={{ name: 'lock' }}
                onPress={Actions.login}
              />
            </View>
          </View>
    
          <Spacer size={10} />
    	 
    
          <View style={[AppStyles.row, AppStyles.paddingHorizontal]}>
            <View style={[AppStyles.flex1]}>
              <Button
                title={'Sign up'}
    			backgroundColor={'#FB6567'}
                icon={{ name: 'face' }}
                onPress={Actions.signUp}
              />
            </View>
          </View>
    
        </Image>
      )

I want the buttons to occupy one row and possibly share 40% - 40% of the space with the rest of the 20% going to the padding. How can i have them occupy one row?.

**Comment by mcnamee** [comment]
Hi @openqubit 
Layout is handled by Flexbox in React Native. Take a look into [React Native's implementation into Flexbox](https://facebook.github.io/react-native/docs/flexbox.html).

Once you've got a basic understanding, you'll be able to make use of some 'quick-styles' I've setup, to do something like:

```js
<View style={[AppStyles.row]}>
   <View style={[AppStyles.flex1]}>
      <Button title={'Sign up'} onPress={Actions.signUp} />
   </View>
   <View style={[AppStyles.flex1]}>
      <Button title={'Login'} onPress={Actions.login} />
   </View>
</View>
```

**Comment by openqubit** [comment]
@mcnamee  Where can i get the list of all icons since i want to use icons in my UI.

**Comment by mcnamee** [comment]
Yep, you can check out the respective repo - [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons).
