### ISSUE TITLE
setTimeout warnings popup repeatedly

### ISSUE THREAD

**Issue by thaibeouu** [mcnamee/react-native-starter-app#84]
Take a look at those images, I don't know where the errors come from
http://i.imgur.com/zvUUrr9l.png
http://i.imgur.com/cb6BTcpl.png

**Comment by mcnamee** [comment]
Hey @thaibeouu 
You're right - that's an annoying issue. I've double checked and it looks as though that warning is coming from the Firebase dependency.

Please let me know if you come to a different conclusion, or find something that we can improve in this repo.
