### ISSUE TITLE
Usage with CRNA of Expo ? 

### ISSUE THREAD

**Issue by rmkpatchaa** [mcnamee/react-native-starter-app#86]
Hi,

Is it possible to port this starter app to [Expo](https://expo.io/) or add it to a [CRNA](https://github.com/react-community/create-react-native-app) app ? 

I've tried with the `exp convert`  (https://docs.expo.io/versions/v17.0.0/guides/exp-cli.html) tool but didn't succeed.

Do someone have experience with it ?

**Comment by mcnamee** [comment]
I'm keen if someone wants to submit a pull request 👍
