### ISSUE TITLE
Way to hide or remove firebase database

### ISSUE THREAD

**Issue by brainahdev** [mcnamee/react-native-starter-app#87]
I have used this Starterkit and its was great to startup for a new comer to react native. Currently I use to check your latest updates and it seems that Firebase database is been added. While I try to run it asks for something mandatory and is there any setting where I can switch off this firebase and I can use my own server for API or DB? Kindly let me know

**Comment by mcnamee** [comment]
Great feedback @brainahdev 
I've just made a few updates which are now in master + updated the README.md for updated getting started instructions.

You're now **not** required to use Firebase; however the code/structure is there for you, if/when you're ready to create you're own user authentication.

User authentication for example, should just be a matter of updating the User Actions (`/src/redux/user/actions.js`), to call your own API and handle the response (in place of the respective Firebase methods).

Let me know what you think

**Comment by rrjanbiah** [comment]
+1

@mcnamee IMHO, it would be better if Firebase is moved as a plugin or adapter. IOW, instant starter app without needing to configure Firebase, as before would be very helpful

**Comment by brainahdev** [comment]
**@mcnamee** Thank you very much for your reply. Will check on the latest update and also yes I think some kind of plugin management will be very helpful

**Comment by mcnamee** [comment]
@rrjanbiah Thanks also for your feedback!

The great thing now (see master branch), is that it will now start up instantly without the need to configure Firebase at all.

Firebase is actually a plugin (NPM module) - this repo only has 3 files that have Firebase boilerplate code (+ `firebase.js`). It's in there to show you how you can make an API and redux work together. And given all the Firebase interaction is abstracted within actions, can be rewritten very easily to use you're own API if needed (eg. perhaps simply changing the Firebase promises to `fetch()` promises?).

**Comment by rrjanbiah** [comment]
@mcnamee 

> The great thing now (see master branch), is that it will now start up instantly without the need to configure Firebase at all.

That's a great news. Will check

**Comment by brainahdev** [comment]
Cool it works..Great
