### ISSUE TITLE
"react-native run-android" isn't working for me

### ISSUE THREAD

**Issue by emiliano-carrillo** [mcnamee/react-native-starter-app#88]
**I get this error:**
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-device-info'.
> failed to find Build Tools revision 25.0.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 3.959 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
 #https://facebook.github.io/react-native/docs/android-setup.html
```

**What shoul I do?**

**Comment by jaga-me** [comment]
Hi Emiliano,

Seems like the SDK Build - Tools is not installed. If you followed the React Native tutorial, it only asked you to install 23.0.1.

You can install v25.0.2 by going to your "Android Studio". Look at the header menu under the SDK Manager as shown:
<img width="1318" alt="screen shot 2017-07-02 at 12 39 56 am" src="https://user-images.githubusercontent.com/17528506/27763894-1b7347aa-5ebf-11e7-875f-127697726a02.png">

Then select "SDK Tools" and at the bottom of that, near the "cancel/ok" buttons, you can select "Show Package Details"

Select the appropriate versions as shown:
<img width="1175" alt="screen shot 2017-07-02 at 12 36 35 am" src="https://user-images.githubusercontent.com/17528506/27763902-492945aa-5ebf-11e7-9629-622dd18060d7.png">

Click "Apply", wait for the install and re-run "react-native run-android"

**Comment by arkilis** [comment]
Or you can find the file `node_modules/react-native-device-info/android/build.gradle` and set 

`buildToolsVersion "23.0.1"`

**Comment by nosizejosh** [comment]
@arkilis  i tried your method, but still unable to get the starter to run.
`Execution failed for task ':react-native-device-info:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\oajos_000\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1`

**Comment by mcnamee** [comment]
Hi @nosizejosh 

First I'd suggest trying @jaga-me solution - which is to ensure you have the required Android SDKs installed.

Next you could look something like [this link](https://stackoverflow.com/questions/32873281/how-to-fix-23-0-1-aapt-exe-finished-with-non-zero-exit-value-1) - as it would appear to be system related.

Feel free to reopen if you have further information you can provide.

For the record, whilst @arkilis solution may work immediately - it's not recommended, as you shouldn't commit `node_modules` under version control. So future you, or even co-workers wouldn't be able to build/use the project without needing to go in a modify specific build files after they've `npm install`'d.
