### ISSUE TITLE
Firebase not connected correctly

### ISSUE THREAD

**Issue by alexborton** [mcnamee/react-native-starter-app#89]
I've followed all the instructions on setting up Firebase but am unable to sign up from my simulator.

The error at the top displays as "Firebase not connected correctly".

Any ideas how to debug this issue?

**Comment by mcnamee** [comment]
Hey @alexborton 
You should only get that error if the .env does not contain credentials.

I have noticed that the dotenv package somewhat caches variables. I was sometimes required to close the RN package and start up again to get the new variables.

Let me know if that resolves!

**Comment by alexborton** [comment]
Thanks @mcnamee but you might have to be a little more specific as to what i need to do to close the RN package; i'm still new to this world!

I have manually deleted all the node_modules and reinstalled after creating the .env file with all the correct details in the correct syntax.

Thanks
