### ISSUE TITLE
Only half screen is used in landscape mode

### ISSUE THREAD

**Issue by obromios** [mcnamee/react-native-starter-app#9]
When I unlock the device orientation and allow the device to go landscape mode, the app only fills the left half the screen, the rest is blank. How do I fix this?

Also, maybe related, when I rotate the screen so it goes back to portrait view, sometimes it shows a unrotated portrait mode.

See below for examples screen shots.

By the way, I have found this app very useful. Thank you.

![screen shot 2016-05-01 at 9 06 26 am](https://cloud.githubusercontent.com/assets/1390233/14939106/6be87c48-0f7c-11e6-9b07-59801d6903b6.png)

![screen shot 2016-05-01 at 9 06 08 am](https://cloud.githubusercontent.com/assets/1390233/14939107/6be9307a-0f7c-11e6-84e0-a929b265e661.png)

**Comment by mcnamee** [comment]
Hi, I'm on holidays away from my computer for the next few days, but will take a look when I return.

If you find a fix in the meantime, feel free to submit a pull request.

Matt

**Comment by obromios** [comment]
Does this [answer](http://stackoverflow.com/a/20321576/1299362) on stackoverflow point in the right direction to solve this problem?

**Comment by mcnamee** [comment]
Hi @obromios 
Sorry for the delay! I've just pushed an upgrade which resolves this. Basically, RN calculates the windowWidth on load and you have to manually ask it to recalculate for things like orientation change.
Instead of doing this, I simply rewrote the styles to use flexbox - which is the better way to do it anyway.

Thanks for raising the issue, to push me along

**Comment by obromios** [comment]
Thank you, I will try it in the next few days and let you know how it goes.


Flexbox fantastic, for the first time I am not dreading having to locate
any elements with CSS.

**Comment by obromios** [comment]
That worked thank you.  Elegant solution ⭐
