### ISSUE TITLE
React Native Web

### ISSUE THREAD

**Issue by brainahdev** [mcnamee/react-native-starter-app#90]
Is there any plugin or update related to web conversion (React Native for Web)? as said the kit seems to be user friendly and if the web feature is added then its great thing so all mobile and web can be achieved with one kit.

**Comment by mcnamee** [comment]
Hi @brainahdev 
It'd be possible to share a bunch of the code across platforms (even if it was just redux and business logic).

A few things to consider:

- **Platform-specific components** (eg. browsers wouldn't know what a `<TextInput />` is, so would need to switch to the web alternative, when bundling for web)
- **Navigation** - I'm sure there'd be a better alternative to React Native Router Flux, that might be able to work across platforms
- **Compilation** - we'd need a way to bundle/compile to the 'web-platform'
- **Styles** - we'd very-likely want to build a responsive website, meaning layout may be very different in some scenarios. So perhaps something like `.web.js` to target web would suffice

You could start by looking at something like [React Native Web](https://github.com/necolas/react-native-web).

More than happy for pull requests if you find a solid way to implement this
