### ISSUE TITLE
react-native-device-info:processReleaseResources

### ISSUE THREAD

**Issue by tuckg** [mcnamee/react-native-starter-app#91]
node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.g
oogle.android.gms\play-services-base\11.0.2\res\drawable\common_google_signin_bt
n_text_light_normal.xml:3:29-92 : No resource found that matches the given name
(at 'drawable' with value '@drawable/common_google_signin_btn_text_light_normal_
background').
* What went wrong:
Execution failed for task ':react-native-device-info:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.E
xecException: Process 'command 'D:\Android\sdk\build-tools\25.0.2\aapt.exe'' fin
ished with non-zero exit value 1

**Comment by mcnamee** [comment]
Hi @tuckg 
Sorry I can't replicate this one. Have you tried the solution proposed over [here](https://github.com/mcnamee/react-native-starter-app/issues/88) at all?

Alternatively, you could remove `react-native-device-info` from `package.json` - it's not actively used. I've only kept in in there, as I used it on almost all projects when I have a custom API, to determine what my users are using.

**Comment by laoxiao79** [comment]
* What went wrong:
Execution failed for task ':react-native-device-info:mergeDebugAndroidTestResources'.
> Error: Failed to crunch file E:\rn_project\DataCockpit\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.0.2\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png into E:\rn_project\DataCockpit\node_modules\react-native-device-info\android\build\intermediates\res\merged\androidTest\debug\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png

**Comment by laoxiao79** [comment]
the same problem

**Comment by mcnamee** [comment]
Hi @laoxiao79 - are you using the latest version of this repo?

The error you've referenced is related to a package called `react-native-device-info` which currently isn't part of this project.
