### ISSUE TITLE
Cannot create .ipa file

### ISSUE THREAD

**Issue by sumairasaeed** [mcnamee/react-native-starter-app#92]
Project archives as a Generic Xcode archive instead of iOS App archive so cannot publish app. Kindly help please

**Comment by mcnamee** [comment]
Hi @sumairasaeed 
We've been able to publish numerous apps to the iOS and Android app stores, where this repo was used as the boilerplate.

Take a look around the web for instructions on publishing iOS apps. The process is fairly generic once the app is built.

Please feel free to reopen if there's a specific error with this repo's code, that someone could help with.
