### ISSUE TITLE
react-native run-android

### ISSUE THREAD

**Issue by vijaemanlapaz** [mcnamee/react-native-starter-app#93]
hi

i run the command "react-native run-android".

see link for the error message

http://imgur.com/a/v7V0D

**Comment by mcnamee** [comment]
Hi @vijaemanlapaz 
May be related to [this issue](https://github.com/mcnamee/react-native-starter-app/issues/88) - please check that you've got v23 of the Android SDK build tools.

**Comment by nosizejosh** [comment]
@mcnamee why should this affect loading or startup?  especially when you try run on device?

**Comment by mcnamee** [comment]
@nosizejosh Because the SDKs are required to build/compile the the code into a runnable app file.
