### ISSUE TITLE
Try to import dotenv variables "API_KEY" which is not defined in any .env files

### ISSUE THREAD

**Issue by rathorebs** [mcnamee/react-native-starter-app#97]
Hi,

I'm unable to run this app in my Android simulator on windows 7, 

### Actual result

![screengrab](https://user-images.githubusercontent.com/9293248/28827799-51387bb8-76ec-11e7-8c94-bdc84fc6aa30.jpg)

1. [Screenshot, logs]

**Comment by thaodx** [comment]
Let copy **.env.sample** to **.env** file and change the configuration variables

**Comment by rathorebs** [comment]
Sounds good!

Now It's working fine.

Thanks :)

**Comment by rapha18th** [comment]
I'm having a similar problem and I do not understand the above solution
