### ISSUE TITLE
A problem occurred configuring project ':react-native-vector-icons'

### ISSUE THREAD

**Issue by tundak** [mcnamee/react-native-starter-app#98]
Getting error when trying `react-native run-android`
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-vector-icons'.
   > failed to find target with hash string 'android-26' in: /opt/android-sdk
```

Working on ubuntu 14.04 64 bit system. let me know if need additional info ?

**Comment by mcnamee** [comment]
The error looks like it's saying that the module `react-native-vector-icons` requires Android SDK/build tools `v26`, but you don't have it installed.

**Comment by YasirPanjsheri** [comment]
@mcnamee hi , I am having the same error. I have this installed already `android SDK tools 26.0.2` `android SDK platform-tools 26.0.0` `Android platform version: API25: Android 7.1.1 (Nougat) revision 3`

**Comment by policz** [comment]
How to resolve the below issue
My app is developed on react-native framework

FAILURE: Build failed with an exception.

What went wrong:
A problem occurred configuring project ':app'.
Could not resolve all dependencies for configuration ':app:_debugApk'.
A problem occurred configuring project ':react-native-vector-icons'.
> No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Get more help at https://help.gradle.org

BUILD FAILED in 5s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
